# Generated by Django 5.1.3 on 2024-11-18 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadedfile',
            name='embedding_path',
            field=models.TextField(blank=True, null=True),
        ),
    ]
