# Generated by Django 5.1.3 on 2024-11-18 12:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_uploadedfile_embedding_path'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uploadedfile',
            name='embedding_created',
        ),
        migrations.RemoveField(
            model_name='uploadedfile',
            name='embedding_path',
        ),
    ]
